### ISSUE TITLE
Drop-in replacement for countrycode dictionary from raw sources

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#1]
@cjyetman 

We could build a drop-in country-year replacement for the countrycode dictionary, built programmatically (as much as possible), from original sources.

Dictionary-related ode would be stored in the utilities folder (ignored on countrycode build), raw data stored in the data/raw folder. 

Download original files first using utilities/download_country-year.R, then merge using utilities/merge_country-year.R. Finally, save country-year.csv to data/.

When we have a good product, we could just copy everything over to countrycode repo.

**Comment by vincentarelbundock** [comment]
I gave you push access here if you want to play around.

**Comment by cjyetman** [comment]
do you consider 'raw' data the exact file that is downloaded from the source, or the processed CSV file ready to be merged with the others? Should we keep both? Should we distinguish them by having different folders or a different prefix/suffix?

**Comment by vincentarelbundock** [comment]
Closing this as the purpose of the repository is now clear.

Getting close to the goal. I ran the ``countrycode`` test suite using the ``dictionary_crossection.csv`` and I only get a couple minor errors (opening issues now).
