### ISSUE TITLE
withdrawn ISO codes not imported

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#12]
Some withdrawn ISO codes are not imported. For instance, East Germany and West Germany used to be 278 and 280 respectively, but now Germany is 276 in iso3n. Such withdrawn codes are not captured by the ISO scraper. Need to determine a robust way of collecting and integrating these withdrawn ISO codes (also for iso3c and iso2c). See https://en.wikipedia.org/wiki/ISO_3166-1_numeric#Withdrawn_codes for more examples.

**Comment by vincentarelbundock** [comment]
I'm not sure we have the responsibility to collect these. CoW's explicit mission is to be comprehensive time-wise. ISO's is not. The current data respects canonical CoW and ISO codes.

**Comment by cjyetman** [comment]
Using the following hypothetical code...
```r
countryyear(source = 'West Germany', year = 1980, orig = 'country.name', dest = 'iso3n')
```
you would get `NA` unless we find a source for West Germany's iso3n code 280 (or manually shove it in there, which would set an unfortunate precedent).

@vincentarelbundock do you think `NA` is an acceptable result, or should we get `280` in there somehow? Is it ok to just add it manually, or does that set an expectation that countryyear will have every code possible even for codes that are no longer in use and no longer part of an official code set? I can see both arguments. West Germany's iso3n `280` is no longer part of the current iso3n code set, so one could argue that if you're working with data that includes countries that are no longer part of the ISO code set, then you should use a different code set that is intended to maintain unique codes even for historical countries.

**Comment by vincentarelbundock** [comment]
Good question.

I lean toward returning NA. Given the project we're now engaged in, it makes more sense to maintain an "up-to-date" or "latest" (for defunct codes) dictionary.

One option might be to manually package some vectors for use in "custom_match" to handle older codes.

**Comment by vincentarelbundock** [comment]
Moving to countrycode repo
