### ISSUE TITLE
docker files

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#13]
@vincentarelbundock can you share your docker files/setup? can/should we add that to the repo?

I'm not opposed to running `R CMD build` and `source('utilities/build.R')` through a docker managed environment to make sure we're on the same page.

**Comment by vincentarelbundock** [comment]
```
# R base image
FROM ubuntu:16.04

# Locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

# System
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install vim sudo htop

# R package dependencies
RUN apt-get -y install libcurl4-openssl-dev libssl-dev 
RUN apt-get -y install libmariadb-client-lgpl-dev 
RUN apt-get -y install gsl-bin libgsl2 libgmp3-dev
RUN apt-get -y install libgsl0-dev # topicmodels
RUN apt-get -y install libfreetype6-dev # showtext
RUN apt-get -y install libxml2-dev
RUN apt-get -y install jags
RUN apt-get -y install pandoc
RUN apt-get -y install poppler-utils # pdftotext

# R packages
RUN echo "deb http://cran.stat.sfu.ca/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
RUN apt-get update
RUN apt-get -y install r-base

# Create an R docker
ENV HOME /home/docker
RUN useradd --create-home --home-dir $HOME docker \
    && chown -R docker:docker $HOME
WORKDIR $HOME
# User needs to be "docker", otherwise permissions on mounted HD don't work
USER docker 

# set the default command
CMD ["bash"]
```

**Comment by cjyetman** [comment]
I messed around with this and got a minimal Dockerfile and made some changes to [`utilities/iso.R`](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/iso.R) so that it can run inside the docker virtual machine. This is related to issues in #4 

Are you aware of the Docker images from [Rocker Project](https://hub.docker.com/u/rocker/)? I think they're a good starting point for R docker images, and their [r-base](https://hub.docker.com/r/rocker/r-base/) image is the ['official' r-base](https://hub.docker.com/_/r-base/) image as far as I can tell. It installs an `install2.r` script that makes it easy to install packages from the Dockerfile.

Dockerfile looks like...
```docker
FROM r-base

RUN apt-get update \ 
    && apt-get install -y --no-install-recommends \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssh2-1-dev \
    bzip2

RUN install2.r --error \ 
    -r 'http://cran.rstudio.com' \
    pacman \
    dplyr \
    RSelenium \
    xml2 \
    rvest \ 
    readr \
    readxl \
    crayon \
    testthat \
    praise \
    countrycode
```

I put this `Dockerfile` in the `utilities/` directory, then build (from the project's root directory) with 
```bash
sudo docker build -t countryyear -f utilities/Dockerfile .
```
then run it interactively with
```bash
docker run -ti --rm -v "$PWD":/home/docker -w /home/docker -u docker countryyear
```
and in that running R instance I'm able to successfully run
```r
source('utilities/iso.R')
```

**Comment by cjyetman** [comment]
Also, to get `utilities/iso.R` working in your Docker image, you may need to install `bzip2`... that seemed to be the problem with my initial tests. The `binman` package was successfully downloading the `phantomjs` file, but it was not unzipping it, and that's why it was not being found.

**Comment by vincentarelbundock** [comment]
Looks great, thanks.

I suppose this is "official" enough so that I don't have to worry to much about maintainability. Will probably switch my own workflow over to this when I find some time.

Good idea to include in the repo.

**Comment by vincentarelbundock** [comment]
Added here: https://github.com/vincentarelbundock/countryyear/commit/299f80bd157016f8e242d0facf26f7687295db17

The get_iso.R script now works on my machine with RSelenium. Thanks!
