### ISSUE TITLE
FIPS, GEC, or GENC

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#14]
According to these, FIPS has been replaced by GEC, and then by GENC.
https://en.wikipedia.org/wiki/FIPS_10-4
http://geonames.nga.mil/gns/html/countrycodes.html

This is a "crosswalk" XLSX file that is updated every quarter which provides a comparison of all 3 GENC codes (2c, 3c, 3n) and GEC codes, all of which are based on ISO 3166, but as with many other codes, have deviations where ISO 3166 falls short of their needs.
http://geonames.nga.mil/gns/html/docs/GENC_ED3U5_GEC_XWALK.xlsx

So, should we have a scraper here for FIPS, GEC, or GENC... or what combination of those?

**Comment by vincentarelbundock** [comment]
I suppose it might be nice to keep fips around for backward compatiblity and so users can interact with older datasets. Would that be a lot of trouble?

**Comment by cjyetman** [comment]
Do you know of an/the official source for FIPS?

**Comment by vincentarelbundock** [comment]
Nope. fips was a contributor PR. I don't have a very strong opinion here. I guess it depends on how strict we want to be with the "all from original sources" principle. We could keep a legacy version of fips from current countrycode.

Do you feel that's undesirable?

**Comment by cjyetman** [comment]
nope... you're the boss ;-)

**Comment by vincentarelbundock** [comment]
My inclination is to say that the cost of leaving the legacy code in there is low for us, but may be useful for some users. So I'll just export a CSV with FIPS codes to the data/sources folders.

**Comment by cjyetman** [comment]
Actually, it looks like GEC maybe was just a new name for FIPS? And in any case [this page](http://geonames.nga.mil/gns/html/gec_updates.html), and specifically [this XLS](http://geonames.nga.mil/gns/html/Docs/GEOPOLITICAL_CODES.xls) file seem to have the last official version of FIPS (April 2010).

Should write a scraper for FIPS based on that (should be super simple)? And then also one for the newer GENC (also super simple)?

**Comment by vincentarelbundock** [comment]
Yeah, that sounds good. Perhaps we should also save the FIPS xls somewhere. If it's discontinued (or renamed), that file may not stay online forever.

**Comment by cjyetman** [comment]
I just made it save in Internet Archive: http://wayback.archive.org/web/20170213021102/http://geonames.nga.mil/gns/html/Docs/GEOPOLITICAL_CODES.xls

**Comment by vincentarelbundock** [comment]
ha! Didn't even realize you could request things like that. Very nice!

**Comment by cjyetman** [comment]
scrapers for FIPS and GENC (and updated CSV files and build script) in [commit 7406c6d](https://github.com/vincentarelbundock/countryyear/commit/7406c6d666d0baacae60e6c96656acfe78530cb2)

**Comment by cjyetman** [comment]
let's leave issue this open until I have a chance to verify/check this FIPS against the version in countrycode

**Comment by cjyetman** [comment]
FYI... the 'FIPS 10' column of the 'APP B' tab in the [XLS file](http://geonames.nga.mil/gns/html/Docs/GEOPOLITICAL_CODES.xls) linked above contains a FIPS code for numerous small island territories for which the existing countrycode dataset does not contain a FIPS code (but does contain a row for the island territory)... e.g. Bermuda and Bouvet Island. Also, there are discrepancies between some of the FIPS codes, e.g. 'KT' for Christmas Island in the XLS and 'CX' for Christmas Island in countrycode.

So, there are definitely problems with simply replacing the legacy 'fips105' code in countrycode with the result from the FIPS scraper that I wrote (particularly if you want to maintain backwards compatibility with the existing countrycode dataset).

**Comment by vincentarelbundock** [comment]
I care more about accuracy with respect to the latest release of a code than backwards compatibility with past translation dicts.

I know nothing about fips,.So I'm happy to defer to your judgment on which version is "best".

**Comment by cjyetman** [comment]
This [PR #22](https://github.com/vincentarelbundock/countrycode/pull/22) 'added missing FIPS codes', including the proper code 'KT' for Christmas Island (for example). It was closed, not merged, but it appears that this [commit](https://github.com/vincentarelbundock/countrycode/commit/be417385178b6ec6331cab59fb92952626024822) the following day was intended to implement the changes, however, at that point there is no fips code for Christmas Island (again, just an example). Then in this next [commit](https://github.com/vincentarelbundock/countrycode/commit/3b5517932a79682314e7e93e83e4455f51a31e85) (a year late), the wrong fips code 'CX' is introduced, and I suppose it's stuck around since then. So, I suspect the discrepancies are due to errors in the legacy countrycode dataset?

Also, apparently this [commit ](https://github.com/vincentarelbundock/countrycode/commit/cb7ced3ea1ca1e09f8e0403af70c4dabaafbfe4a)changed 'fips104' to 'fips105' for no explicit reason. As far as I can tell, FIPS 10-5 never existed.

**Comment by cjyetman** [comment]
and if it wasn't obvious already, based on that, my suggestion would be to use the result from the new scraper and scrap the legacy fips codes (and rename it to either 'fips104' or just 'fips')

**Comment by vincentarelbundock** [comment]
I'm glad you're now enforcing more rigorous development practices.

The early years of countrycode were super sloppy.

If I'm reading you right, this file (the scrape code you've written which I wrapped in a function) produces "best" results. Going forward, we're going with the output of this function, and we can close this issue. 

Right?

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countryyear/blob/master/code/get_fips.R

**Comment by cjyetman** [comment]
yup. just finally following up on my 'leave open till I verify FIPS' comment. closing now

**Comment by vincentarelbundock** [comment]
Thanks again for all your help. This is really starting to take shape.

Still need to figure out the best way to make a cross-section dictionary from the country-year. Also, need to triple check the CoW/Polity conversion decisions. After that, there will still be some manual/static codes, but most will be automatized.
