### ISSUE TITLE
find and scrape well known 'continent' convention/s

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#19]
Find official sources for well known 'continent' conventions and write scrapers for them.

here's one for starters:
[United Nations Statistics Division](https://unstats.un.org/unsd/methodology/m49/#geo-regions) (5 continents plus Antartica; 17 sub-continents plus Antartica)

**Comment by vincentarelbundock** [comment]
```
> library(WDI)
> dat = WDI(country = 'all', extra = TRUE)
> unique(dat$region)
[1] Aggregates                 Europe & Central Asia     
[3] Middle East & North Africa South Asia                
[5] Latin America & Caribbean  Sub-Saharan Africa        
[7] East Asia & Pacific        North America             
[9] <NA>  
```

**Comment by cjyetman** [comment]
here's a good source for the official World Bank regions in XLS...
http://databank.worldbank.org/data/download/site-content/CLASS.xls

linked from...
https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups

**Comment by vincentarelbundock** [comment]
These codes are all available using the WDI() command and the extra=TRUE flag.

**Comment by cjyetman** [comment]
but do they include a list of countries that each group contains?

**Comment by cjyetman** [comment]
nevermind, I just tried it, and yes, it does

**Comment by ktheyss** [comment]
I got directed by a colleague to this website for continents. http://dev.maxmind.com/geoip/legacy/codes/country_continent/ 

From our epidemiological work on infectious diseases, we learned that there is no consensus. For examply Cyprus is Europe or West-Asia given different sources (WHO e.g)

**Comment by cjyetman** [comment]
Gazetteer of Planetary Nomenclature: https://planetarynames.wr.usgs.gov/Abbreviations

Africa (AF)
Antarctica (AN)
Asia (AS)
Europe (EU)
North America (NA)
Oceania (OC)
South and Central America (SA)

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/150

Moving everything there as I plan to close development on countryyear today.
