### ISSUE TITLE
FAO code incomplete

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#20]
Hi – I just tried to use your countrycode package to convert FAO codes to ISO2, but several of the FAO codes are missing (American Samoa is 5, Bermuda is 17, for example).
Perhaps the package needs updating?
 
Cheers,
Dan
 
[FAOSTAT_data_4-28-2017.zip](https://github.com/vincentarelbundock/countryyear/files/965039/FAOSTAT_data_4-28-2017.zip)

OK, I’m plotting agricultural data from FAOSTAT which provides the code and name of the geographic region.
I downloaded the attached table from http://www.fao.org/faostat/en/#data/QC
Hope it helps.

Dan

**Comment by cjyetman** [comment]
We're currently using this as the source:  http://www.fao.org/countryprofiles/iso3list/en/

We'll have to review what the differences are between the two links

**Comment by cjyetman** [comment]
at this page: http://www.fao.org/countryprofiles/geopolitical-ontology/download/en/

I found a link to this XLSX file titled "All territories valid the current year": http://www.fao.org/fileadmin/user_upload/countryprofiles/Excel/AllTerritoriesValidCurrentYear.xlsx

which includes the FAOSTAT_CODE for American Samoa and Bermuda, unlike the list found at http://www.fao.org/countryprofiles/iso3list/en/ which we're currently using. Maybe we should adapt the FAO scraper to use the XLSX file?

**Comment by vincentarelbundock** [comment]
Makes sense to me. End of semester means I won't look I to that for a whole though. Sorry!

**Comment by cjyetman** [comment]
@vincentarelbundock the code below could be a drop-in replacement for [get_fao.R](https://github.com/vincentarelbundock/countryyear/blob/master/code/get_fao.R) using the XLSX mentioned above as the source , but I didn't commit it without running it by you first because...

1. the current version of get_fao.R manually removes Bassas da India and Gaza Strip, presumably because there is no equivalent in the countryyear regex set
2. the new XLSX source includes Bassas da India and Gaza Strip, as well as many other islands/territories/etc. that are not in the countryyear regex set

The code below just drops anything that is not found by `CountryToRegex()`, but maybe you want to have more control over that?

```r
get_fao = function() {
    url <- 'http://www.fao.org/fileadmin/user_upload/countryprofiles/Excel/AllTerritoriesValidCurrentYear.xlsx'
    tmp_xlsx <- tempfile(fileext = '.xlsx')
    download.file(url, tmp_xlsx, quiet = TRUE)
    
    fao <- readxl::read_excel(tmp_xlsx) %>% 
        dplyr::select(fao.name = SNAME_EN,
                      fao = FAOSTAT_CODE,
                      undp = UNDP_CODE, # United Nations Development Programme
                      gaul = GAUL_CODE) %>% # Global Administrative Unit Layers
        dplyr::mutate_each(funs(as.integer), fao, gaul) %>% 
        dplyr::mutate(country.name.en.regex = CountryToRegex(fao.name)) %>% 
        dplyr::filter(!is.na(country.name.en.regex))
    
    unlink(tmp_xlsx)
    return(fao)
}
```

**Comment by vincentarelbundock** [comment]
In general, I prefer to drop explicitly rather than implicitly, but it's not a big deal.

Thanks for this. Perhaps we should comment out the other code and drop this in just in case we want to revert back (and don't feel like sifting through git commits.

**Comment by cjyetman** [comment]
in dc07f6fbf76d9c9dd8144e20c2a81e62734ce846 I commented out the old code, implemented the new code which pulls from the FAO XLSX file instead (which is more complete), and explicitly remove the islands and territories that we don't have regexes for ([code/get_fao.R#L6-L18](https://github.com/vincentarelbundock/countryyear/blob/master/code/get_fao.R#L6-L18))
