### ISSUE TITLE
add Unicode's country name CLDR locale variations

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#21]
originally discussed in vincentarelbundock/countrycode#148

**Comment by cjyetman** [comment]
9b1db7c0c0b47dfece5da4cb5761cfba920e79e7 adds the CLDR country name language/culture variations, however, the following issues need to be discussed/decided...

1. The language/culture codes used by CLDR have a dash in them, e.g. 'en-GB' and 'en-US-POSIX'. The current script converts all '-' to '_', e.g. 'en_GB' and 'en_US_POSIX'. That conforms better to R's standard locale reference (see `Sys.getlocale('LC_CTYPE')`) and makes for valid column names in the resulting data frame. I'm open to other suggestions though.

2. For each language/culture locale, there is a full set of names, plus possible 'alt-short' or 'alt-variant' variations of specific country names. In order to make these available, the script creates a column for 'cldr.short' and 'cldr.variant' for each locale, using the 'alt-short' or 'alt-variant' names where available and otherwise copying in the default country name for the given locale. This results in 3 times as many columns and a lot of duplication. I'm open to better ideas of handling this.

3. The size of this makes dictionary_panel.csv huge (321.6 MB), and other things quite large.

**Comment by cjyetman** [comment]
[code/build.R](https://github.com/vincentarelbundock/countryyear/blob/master/code/build.R) works locally on my machine, but not in the Docker VM. [L111](https://github.com/vincentarelbundock/countryyear/blob/master/code/build.R#L111) runs for too long and times out. I'm tired of fighting with it for now, so I'm removing CLDR from the build process in 2b3183dd0c654cdb5632adadded6334562b0cc41 until we find a more efficient way of doing this
```r
# Cross-section
f = function(x) last(x[!is.na(x)]) # keep latest code for each regex
dictionary %>% 
    dplyr::arrange(country.name.en.regex, year) %>%
    dplyr::select(-year) %>%
    dplyr::group_by(country.name.en.regex) %>%
    dplyr::summarize_each(funs(f)) %>%
    readr::write_csv('data/dictionary_crosssection.csv', na = '')
```

**Comment by vincentarelbundock** [comment]
Closing. The dictionary is not huge when stored in binary format, so we can package it on CRAN, I think.
