### ISSUE TITLE
Load from backup as default

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#23]
This is a discussion item (I'm already implementing this).

I've already seen lots of broken data sources upstream. As a default, countrycode will build the dictionary from date-stamped backups. I just don't want to deal with upstream breakage from 15 different sources. '

We will always keep a copy of the scrape scripts, and there will be an easy switch to update the original source whenever necessary.

**Comment by cjyetman** [comment]
Good idea. These URL's are bound to break eventually.
