### ISSUE TITLE
default settings of read.csv are dangerous

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countryyear#5]
`read.csv`, by default, converts 'NA' strings to `<NA>`, which is a very common problem here because of Namibia's common 2 character code 'NA'. This can be avoided by using `read.csv`'s `na.strings = ''` argument. 

Additionally by default, read.csv converts strings to factors, adds row names, does not mark character strings with an encoding, relies on `type.convert` to determine the column classes, etc.

See [this script in `countrycode`](https://github.com/vincentarelbundock/countrycode/blob/master/utilities/prep_data.R#L4-L9) for how contorted it is to get to sane options.

I propose that we either write a read.csv wrapper function with appropriate options already set and always use that, or determine the best settings and be vigilant about sticking to them always.

Alternatively, we could use Hadley's [`readr::read_csv`,](https://github.com/tidyverse/readr) which has sane defaults, other than converting 'NA' to `<NA>`, which still has to be turned off manually.

**Comment by vincentarelbundock** [comment]
I had never really had much use for the readr package, but you make a compelling case. I say let's go with ``write_csv``.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countryyear/commit/8550889acbef96bf6cf67d20417019e31d38709d
