### ISSUE TITLE
Improve regexes to take care of special cases

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#7]
I think we're getting close to the goal, here.

Currently, we're using english regexes to uniquely identify countries in all the datasets. There are some cases where that doesn't work and where the original country names need to be massaged. This is currently done source-by-source, in the source-specific scraping scripts.

Eventually, we'll want to just improve the regexes.

Also, we want:

- Tests of the finished dictionary (duplicates, etc.)
- Migrate the English and German regexes as a standalone CSV file

Just pinging @cjyetman in case you care to look (no pressure)

**Comment by cjyetman** [comment]
are there any other source/destination codes that you want to include?

**Comment by vincentarelbundock** [comment]
At minimum, I'd like to replicate current capability. So here's what's missing in the current version of dictionary.csv

```
 [1] "ar5"                   "continent"             "country.name.de"      
 [4] "country.name.de.regex" "eu28"                  "eurocontrol_pru"      
 [7] "eurocontrol_statfor"   "fips105"               "icao"                 
[10] "icao_region"           "imf"                   "p4_ccode"             
[13] "p4_scode"              "region"                "un"                   
[16] "wb_api2c"              "wb_api3c"
```

**Comment by vincentarelbundock** [comment]
p4_scode have just been renamed, obviously.

**Comment by cjyetman** [comment]
the current WB importer uses a response from the API, so that should actually create `wb_api2c` and `wb_api3c`. I have code that generates the non-API WB codes based on a file downloadable from http://databank.worldbank.org which I will merge later.

**Comment by cjyetman** [comment]
I have a project that I recently started that essentially offers lists of member states of specific groups. It's here https://github.com/cjyetman/memberstates

My goal there is to be able to run the scripts only once every 6 months or so, they will scrape everything from some canonical source/s, compare the results to the existing lists, then notify/warn of any changes which can then be verified manually, and then the old list can be overwritten with the validated changes and everything prepared for a new release.

1. my strategy there is similar to what you're doing here, so some of what I have done there might be instructive (e.g. I save the source URL and access date in attributes for everything)
2. some of the destination codes here are actually groupings, so some of the code over there may be easy to port over to here

**Comment by vincentarelbundock** [comment]
I like this a lot. Also obviates the need for some of the countrycode I have at the moment.

**Comment by cjyetman** [comment]
beginning a list of regex fixes that need to be made:
- [ ] 'Micronesia' should convert/match to 'Federated States of Micronesia'
- [ ] 'Germany East' should convert/match to 'East Germany'
- [ ] 'Korea North' should convert/match to 'North Korea'

**Comment by vincentarelbundock** [comment]
Fixed Germany East and Korea North.

There was discussion of Micronesia here: https://github.com/vincentarelbundock/countrycode/issues/71

I think the conclusion was that it should *not* match Federated States of Micronesia.

Let's open issues for each problematic regex.

**Comment by vincentarelbundock** [comment]
BTW, regexes are now hosted in ``data/dictionary_static.csv``
